version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: social-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5232:5432"
    volumes:
      - social-data:/var/lib/postgresql/data

volumes:
  social-data:
